### ISSUE TITLE
k.sh 대체물 만들기

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/.dotfiles#17]
1. 빠를것
2. fish 컴패티블

아마도 그냥 바이너리로 만들면 될거같다

**Comment by wookayin** [comment]
Go 로 만들면 될거같다

**Comment by simnalamburt** [comment]
이름을 `l` 이라고 지은다음에, `alias l=ls -lah` 대체하죠

**Comment by simnalamburt** [comment]
https://github.com/ogham/exa

**Comment by wookayin** [comment]
I also have been using it! Enjoy :)

**Comment by simnalamburt** [comment]
문제는 https://github.com/ogham/exa/issues/116 이거를 고치고싶은데 귀찮다는점입니다 ㅠ
