### ISSUE TITLE
zsh compinit function 불러오기 실패 도움 문의

### ISSUE THREAD

**Issue by mu-hun** [simnalamburt/.dotfiles#44]
최근에 플러그인 관리를 oh-my-zsh 에서 zinit 로 바꾸면서 simnalamburt 님 zshrc 의 특정 라인을 참고했습니다.

> 참고한 부분: https://github.com/x86chi/.dotfiles/blob/84d8367/.zshrc#L52-L55
> simnalamburt 님 레퍼런스: https://github.com/simnalamburt/.dotfiles/blob/8cc59a1/.zshrc#L45-L48

zsh completion 설정과 연관이 있는 오류 로그를 쉘을 새로 열 때마다 보고 있는데... 검색으로 사례를 찾지 못해서 이슈로 도움을 요청드립니다.

오류 로그만 표시 될 뿐 사용상의 버그는 없습니다.

```
Error: The compinit function hasn't been loaded, cannot do compdef replay.
Running compdef: _yarn yarn
```
---

몇년 전부터 simnalamburt 님 dotfiles 를 참고해서 관리하고 있는데, 양질의 설정을 오픈소스로 올려주셔서 감사드립니다.

**Comment by simnalamburt** [comment]
에러메시지가 발생하는 라인: 
https://github.com/zdharma-continuum/zinit/blob/e5bb1c506a60fbfd72a137377c7c302931b948f5/zinit.zsh#L1879

`compdef` 함수가 정의되지 않았을때 발생하는데, `compinit`을 하기 전에 `zinit cdreplay`를 실행하는게 아닌지 의심됩니다

https://github.com/simnalamburt/.dotfiles/blob/b90c65f16e60e3c1700f9885515ec30148ccc4e8/.zshrc#L45

이걸 참고하셔서 `zinit cdreplay` 앞에 `autoload -Uz compinit; compinit` 을 추가해보세요

**Comment by simnalamburt** [comment]
아 보니까 이미 하고계시네요 이상하네요

zshrc를 고쳐서 해당 라인에서 compdef 함수가 정의되어있는지, 안되어있다면 왜 안되는지 이런거를 디버깅해봐야할거같습니다
